0,*,(INITIALIZE)
1,*,(move sink counter)
2,*,(take knife counter)
3,*,(move counter sink)
4,*,(move sink counter)
5,*,(move counter sink)
6,*,(put knife sink)
7,*,(move sink counter)
8,*,(take carrot counter)
9,*,(move counter sink)
10,*,(move sink counter)
11,*,(put carrot counter)
12,*,(move counter sink)
13,*,(take knife sink)
14,*,(move sink counter)
15,*,(move counter sink)
16,*,(put knife sink)
17,*,(take knife sink)
18,*,(put knife sink)
19,*,(move sink counter)
20,*,(move counter sink)
21,*,(move sink counter)
22,*,(take carrot counter)
23,*,(move counter sink)
24,*,(move sink counter)
25,*,(move counter sink)
26,*,(put carrot sink)
27,*,(FINISHED)
