(define (problem r218pdev-simple)
    (:domain r218ddev)
  (:init
   (is-visible-from scr2 seatA)
   (is-visible-from scr3 seatA)
   (is-visible-from scr1 seatB)
   (is-visible-from scr2 seatB)
   (is-visible-from scr3 seatB)
   (is-visible-from scr1 seatC)
   (is-visible-from scr2 seatC)
   (is-projector-for prj1 scr1)
   (is-projector-for prj2 scr2)
   (is-projector-for prj3 scr3)
   (has nb1 doc1)
   (has nb2 doc2)
   (has nb3 doc3)
   (is-wired nb1 vga-out-port i1)
   (is-wired nb2 vga-out-port i2)
   (is-wired nb3 vga-out-port i3)
   (is-wired prj1 vga-in-port o1)
   (is-wired prj2 vga-in-port o2)
   (is-wired prj3 vga-in-port o3)
   (is-open o1)
   (is-open o2)
   (is-open o3)
   (is-at alice seatB)
   (is-at bob seatA)
   (is-at charlie seatC)
   )
  (:goal (and (can-see alice doc1)
	      (can-see bob doc1)
	      (can-see alice doc2)
	      (can-see alice doc3)
	      (can-see charlie doc3)
	      )
	 )
  )

	 